server:
  ip: localhost
  port: 8889
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/disaster_relief_materials?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #连接池名
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间 默认十分钟
      idle-timeout: 180000
      # 最大连接数
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 最大存活时间
      max-lifetime: 180000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用的查询测试语句
      connection-test-query: SELECT 1
  redis:
    host:
    port:
    password:

# Mybaits-plus 配置
mybatis-plus:
  # mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 别名生效文件夹
  type-aliases-package: com.ma.disaster.pojo
  global-config:
    db-config:
      # 逻辑删除
      logic-not-delete-value: 1
      logic-delete-value: 0
  configuration:
    #关闭自动驼峰命名
    map-underscore-to-camel-case: false

# Mysql 打印
logging:
  level:
    com.ma.disaster.mapper: debug

files:
  upload:
    path: G:/code/disaster/image